//
//  TaskDetailFormatter.swift
//  CoreDataProject
//
//  Created by Oguz Tandogan on 24.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TaskDetailFormatter {
}

// MARK: - Extensions -

extension TaskDetailFormatter: TaskDetailFormatterInterface {
}
