//
//  TaskDetailWireframe.swift
//  CoreDataProject
//
//  Created by Oguz Tandogan on 24.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TaskDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "TaskDetail", bundle: nil)

    // MARK: - Module setup -

    init(taskDetails: Tasks) {
        let moduleViewController = storyboard.instantiateViewController(ofType: TaskDetailViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = TaskDetailFormatter()
        let interactor = TaskDetailInteractor()
        let presenter = TaskDetailPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self, taskDetails: taskDetails)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TaskDetailWireframe: TaskDetailWireframeInterface {
    
    func navigateToTasksList() {
        navigationController?.popToRootWireframe()
    }
}
