//
//  TaskDetailInteractor.swift
//  CoreDataProject
//
//  Created by Oguz Tandogan on 24.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import CoreData

final class TaskDetailInteractor {
}

// MARK: - Extensions -

extension TaskDetailInteractor: TaskDetailInteractorInterface {
    
    func deleteItem(deletedTask: NSManagedObject,
                    completion: @escaping () -> ()) {
        guard let managedContext = CoreDataStore.managedObjectContext else { return }
        
        let fetchedRequest = NSFetchRequest<NSFetchRequestResult>(entityName: "Tasks")
        fetchedRequest.returnsObjectsAsFaults = false
        do {
            managedContext.delete(deletedTask)
            try managedContext.save()
            completion()
        } catch let error{
            print(error.localizedDescription)
        }
    }
    
    func updateItem(updatedTask: NSManagedObject,
                    newTaskName: String,
                    newTaskDetail: String) {
        guard let managedContext = CoreDataStore.managedObjectContext else { return }
        
        let fetchedRequest = NSFetchRequest<NSFetchRequestResult>(entityName: "Tasks")
        fetchedRequest.returnsObjectsAsFaults = false
        do {
            updatedTask.setValue(newTaskName, forKey: "taskName")
            updatedTask.setValue(newTaskDetail, forKey: "taskDetail")
            try managedContext.save()
        } catch let error{
            print(error.localizedDescription)
        }
    }
    
    
}
