//
//  TaskDetailViewController.swift
//  CoreDataProject
//
//  Created by Oguz Tandogan on 24.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TaskDetailViewController: UIViewController {
    
    @IBOutlet weak var taskName: UITextField!
    @IBOutlet weak var taskDetail: UITextField!
    
    
    // MARK: - Public properties -
    
    var presenter: TaskDetailPresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    private func setupUI() {
        loadTaskDetails()
    }
    
    private func loadTaskDetails() {
        taskName.text = presenter.getTaskName()
        taskDetail.text = presenter.getTaskDetail()
    }
    
    @IBAction private func saveButtonTapped(_ sender: Any) {
        guard let newTaskName = taskName.text,
              let newTaskDetail = taskDetail.text else { return }
        presenter.getChangedTaskName(taskName: newTaskName, taskDetail: newTaskDetail)
    }
    
    @IBAction private func deleteButtonTapped(_ sender: Any) {
        presenter.deleteTask()
    }
    
    
}

// MARK: - Extensions -

extension TaskDetailViewController: TaskDetailViewInterface {
    
    
}
